#!/usr/bin/env bash
# Configure Nginx server 2 web-02 to be identical to web-01 and add header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

#add header
sudo sed -i '/http {/a add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo nginx -s reload
sudo service ngnix restart

