#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
range=100
for i in $(seq $range);
do
	if ((i%5 == 0 && i%3 == 0))
	then
		echo "FizzBuzz"
	elif ((i%5 == 0))
	then
		echo "Buzz"
	elif ((i%3 == 0))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
