#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hours=0
minutes=1
while ((hours<=12));
do
	printf "%s %d\n" "Hour:" "$hours"
	minutes=1
	while ((minutes<60))
	do
		echo $minutes
		((minutes++))
	done
	((hours++))
done
